island:
  gui-lore:
    uncreated:
      normal-nearspawn:
        title: §2Create Normal Near Spawn
        lore: |
          Test line 1
          Test line 2
      normal-faraway:
        title: §2Create Normal Far Away
        lore: ''
      normal-random:
        title: §2Create Normal Random
        lore: ''
      square-nearspawn:
        title: §2Create Square Near Spawn
        lore: ''
      square-faraway:
        title: §2Create Square Far Away
        lore: ''
      square-random:
        title: §2Create Square Random
        lore: ''
    created:
      information:
        title: ''
        lore: ''
      level:
        title: ''
        lore: ''
      challenges:
        title: ''
        lore: ''
      members:
        title: ''
        lore: ''
      trusted-players:
        title: ''
        lore: ''
      biome:
        title: ''
        lore: ''
      lock:
        title: ''
        lore: ''
      pvp:
        title: ''
        lore: ''
      warp:
        title: ''
        lore: ''
      shop:
        title: ''
        lore: ''
      log:
        title: ''
        lore: ''
      set-home:
        title: ''
        lore: ''
      set-warp:
        title: ''
        lore: ''
      leave:
        title: ''
        lore: ''
      restart:
        title: ''
        lore: ''