island:
  gui-lore:
    uncreated:
      normal-nearspawn:
        title: '&2Create Normal Near Spawn'
        lore: |
          &7Click to create a normal island
          &7near the spawn area.
      normal-faraway:
        title: '&2Create Normal Far Away'
        lore: |
          &7Click to create a normal island
          &7far away from other islands.
      normal-random:
        title: '&2Create Normal Random'
        lore: |
          &7Click to create a normal island
          &7in a random location.
      square-nearspawn:
        title: '&2Create Square Near Spawn'
        lore: |
          &7Click to create a square island
          &7near the spawn area.
      square-faraway:
        title: '&2Create Square Far Away'
        lore: |
          &7Click to create a square island
          &7far away from other islands.
      square-random:
        title: '&2Create Square Random'
        lore: |
          &7Click to create a square island
          &7in a random location.
      join-island:
        title: '&2Join an Island'
        lore: |
          &7Click to view a list of islands
          &7that you can request to join.
    created:
      information:
        title: ''
        lore: ''
      level:
        title: ''
        lore: ''
      challenges:
        title: ''
        lore: ''
      members:
        title: ''
        lore: ''
      trusted-players:
        title: ''
        lore: ''
      biome:
        title: ''
        lore: ''
      lock:
        title: ''
        lore: ''
      pvp:
        title: ''
        lore: ''
      warp:
        title: ''
        lore: ''
      shop:
        title: ''
        lore: ''
      log:
        title: ''
        lore: ''
      set-home:
        title: ''
        lore: ''
      set-warp:
        title: ''
        lore: ''
      leave:
        title: ''
        lore: ''
      restart:
        title: ''
        lore: ''